## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [1]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [133]:
# your code here
#model1 = nn.Sequential(OrderedDict([
#    ('hidden', nn.
#]))
model1 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2, 3)),
    ('sigmoid1', nn.Sigmoid()),
    ('hidden2', nn.Linear(3, 2)),
    ('sigmoid2', nn.Sigmoid())
]))

model2 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2,2)),
    ('sigmoid1', nn.Sigmoid()),
    ('hidden2', nn.Linear(2,1)),
    ('relu1', nn.ReLU()),
]))

In [134]:
print(model1)
print(model2)

Sequential(
  (hidden1): Linear(in_features=2, out_features=3, bias=True)
  (sigmoid1): Sigmoid()
  (hidden2): Linear(in_features=3, out_features=2, bias=True)
  (sigmoid2): Sigmoid()
)
Sequential(
  (hidden1): Linear(in_features=2, out_features=2, bias=True)
  (sigmoid1): Sigmoid()
  (hidden2): Linear(in_features=2, out_features=1, bias=True)
  (relu1): ReLU()
)


In [135]:
# your code here
#data_in = torch.tensor( ...
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [136]:
# your code here
# data_target = torch.tensor( ...
data_target = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [137]:
# your code here
# criterion = 
# optimizer = 
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model1.parameters(), lr=0.3)

criterion2 = nn.BCELoss()
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.1)

In [138]:
# your code here
# Train the model
for epoch in range(100000):
    optimizer.zero_grad()
    output = model1(data_in)
    loss = criterion(output, data_target)
    loss.backward()
    optimizer.step()
"""
for epoch in range(10000):
    optimizer2.zero_grad()
    output = model2(data_in)
    loss = criterion2(output, data_target)
    loss.backward()
    optimizer2.step()
"""

'\nfor epoch in range(10000):\n    optimizer2.zero_grad()\n    output = model2(data_in)\n    loss = criterion2(output, data_target)\n    loss.backward()\n    optimizer2.step()\n'

In [139]:
# your code here
# visualize the resuts
with torch.no_grad():
    output = model1(data_in)
    loss = criterion(output, data_target)
    acc = ((output> 0.5) == data_target).float().mean()
print("Model1 - Loss: {}, Accuracy: {}".format(loss, acc))

"""
with torch.no_grad():
    output = model2(data_in)
    loss = criterion2(output, data_target)
    acc = ((output> 0.5) == data_target).all(dim=1).float().mean()
print("Model2 - Loss: {}, Accuracy: {}".format(loss, acc))
"""

Model1 - Loss: 0.00016659111133776605, Accuracy: 1.0


'\nwith torch.no_grad():\n    output = model2(data_in)\n    loss = criterion2(output, data_target)\n    acc = ((output> 0.5) == data_target).all(dim=1).float().mean()\nprint("Model2 - Loss: {}, Accuracy: {}".format(loss, acc))\n'

In [140]:
# your code here
# print model wights
print("Weights Model1:")
for name, param in model1.named_parameters():
    if 'weight' in name:
        print(name, param)
"""
print("Weights Model2:")
for name, param in model2.named_parameters():
    if 'weight' in name:
        print(name, param)
"""

Weights Model1:
hidden1.weight Parameter containing:
tensor([[ 0.5842, -0.1072],
        [ 6.5086,  6.3663],
        [-6.0663, -6.1794]], requires_grad=True)
hidden2.weight Parameter containing:
tensor([[ 0.6074,  3.6929, -9.8531],
        [-6.7119,  9.5158,  9.2748]], requires_grad=True)


'\nprint("Weights Model2:")\nfor name, param in model2.named_parameters():\n    if \'weight\' in name:\n        print(name, param)\n'